import React from 'react';
import image_manager from '../../actions/image-manager';
import iPhoneModel from '../../constant/iPhoneModel'


test('image manager', () => {
    for(let model of Object.keys(iPhoneModel)) {
        for(let color of Object.keys(iPhoneModel[model])) {
            const tests = {
                "iPhone": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    'Package': []
                },
                "iPhone 3G": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    'Package': [3,1]
                },
                "iPhone 3GS": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    'Package': []
                },
                "iPhone 4": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 4S": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 5": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5],
                    'ImeiBackSide': [1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 5c": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5],
                    'ImeiBackSide': [1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 5s": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5],
                    'ImeiBackSide': [1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 6": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5],
                    'ImeiBackSide': [1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 6 Plus": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5],
                    'ImeiBackSide': [1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 6s": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 3],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "Touch3D": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 6s Plus": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 3],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "Touch3D": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone SE": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5],
                    'ImeiBackSide': [1],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "HeadphoneJack": [],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [3,4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 7": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 3],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "Touch3D": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 7 Plus": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 3],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "Touch3D": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 8": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 3],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "Touch3D": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone 8 Plus": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 3],
                    "ButtonsAndVibration": [1, 2, 3],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "Touch3D": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                },
                "iPhone X": {
                    "About": [1, 2],
                    "Appearance": [1, 2, 3],
                    "WaterSensor": [1],
                    "IMEI": [2, 5, 3],
                    "ButtonsAndVibration": [1, 2],
                    "Sensor": [1],
                    "Sensor_Self": [1],
                    "Touch3D": [1],
                    "iCloud": [1],
                    "Flash": [1],
                    "Speaker": [1],
                    "CompassAndGsensor": [1,2],
                    "Camera": [1],
                    "TouchIDorFaceID": [1],
                    "WiFi": [1],
                    "Bluetooth": [1],
                    "Microphone": [1,2],
                    "CallAndProximitySensor": [4],
                    "CellStatus": [1],
                    "Call": [1,2],
                    "Charging": [1],
                    "Warranty": [1,2,3],
                    "Package": [1,2,3,4,5,6,7,8]
                }
            };
            for (let test of Object.keys(tests[model])) {
                for (let number of tests[model][test]) {
                    expect(
                        image_manager(test, number)(null, () => {
                            return {
                                current_iphone: {
                                    model,
                                    color
                                },
                                locale: {

                                }
                            }
                        })
                    ).not.toEqual({
                        src: `../assets/img/default.png`,
                        width: 365,
                        height: 710
                    });
                }
            }
        }
    }
});